# Use an official Python runtime as a base image
FROM python:3.11.6-bookworm

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the celery worker
CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=info", "-P", "gevent"]
