"""add_finished_at_column_to_task_model

Revision ID: 9e6216489195
Revises: 81ad10ef1f4d
Create Date: 2023-10-19 00:50:00.081049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6216489195'
down_revision: Union[str, None] = '81ad10ef1f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'finished_at')
    # ### end Alembic commands ###
